### ISSUE TITLE
导出cmake配置

### ISSUE THREAD

**Issue by FrankXie05** [winsoft666/zoe#27]
既然生成了lib并且导出的宏定义，那不打算导出cmake的find_package()么？
https://github.com/winsoft666/zoe/blob/28bf5d06629e7e5102a704a5a3589e070e4f158d/src/CMakeLists.txt#L62
https://github.com/winsoft666/zoe/blob/28bf5d06629e7e5102a704a5a3589e070e4f158d/include/zoe/zoe.h#L31

**Comment by winsoft666** [comment]
感谢你的pr

**Comment by FrankXie05** [comment]
Fixed by PR https://github.com/winsoft666/zoe/pull/28
