### ISSUE TITLE
[security] Insecure connections, TLS/SSL disabled

### ISSUE THREAD

**Issue by ovaar** [winsoft666/zoe#29]
When requesting data the libcurl option `CURLOPT_SSL_VERIFYHOST` and `CURLOPT_SSL_VERIFYPEER` are explicitly disabled.

see `EntryHandler::requestFileInfo` and `Slice::start`

```cpp
CHECK_SETOPT1(curl_easy_setopt(curl_, CURLOPT_SSL_VERIFYHOST, 0L));
CHECK_SETOPT1(curl_easy_setopt(curl_, CURLOPT_SSL_VERIFYPEER, 0L));
```

I hereby quote the cURL documentation

[CURLOPT_SSL_VERIFYPEER](https://curl.se/libcurl/c/CURLOPT_SSL_VERIFYPEER.html)
> WARNING: disabling verification of the certificate allows bad guys to man-in-the-middle the communication without you knowing it. Disabling verification makes the communication insecure. Just having encryption on a transfer is not enough as you cannot be sure that you are communicating with the correct end-point.

**Comment by winsoft666** [comment]
It seems like I need to give the user an option to enable or disable SSL verify.

**Comment by winsoft666** [comment]
I have added CA/Host verify options.
