### ISSUE TITLE
3.2 version not marked as released

### ISSUE THREAD

**Issue by AbrilRBS** [winsoft666/zoe#34]
Hi! In [Conan Center Index](https://github.com/conan-io/conan-center-index/pull/25615) we are adding (@toge is doing most of the work!) the latest tagged 3.2 version, but we noticed that 3.2 is not yet marked as a release. Is this just an oversight, or should we wait until you release it oficially? Thanks!

**Comment by winsoft666** [comment]
Do you mean submitting version 3.2 to the vcpkg repository?

**Comment by winsoft666** [comment]
"we noticed that 3.2 is not yet marked as a release"

As I known, I have release v3.2.
