### ISSUE TITLE
Version 3.5 was tagged as 3.4 in CMakeLists

### ISSUE THREAD

**Issue by AbrilRBS** [winsoft666/zoe#36]
Hi again!

I was reviewing https://github.com/conan-io/conan-center-index/pull/25978 to add the latest version to Conan Center Index, and we realized that 3.5 was released as 3.4 in the CMakeLists.txt, see https://github.com/winsoft666/zoe/blob/v3.5/CMakeLists.txt#L22

cc @toge

**Comment by winsoft666** [comment]
This issue has been fixed.
